services:
#    comments.example:
#        class: ApiBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    api.admin.comment:
        class: ApiBundle\Admin\CommentAdmin
        arguments: [~, ApiBundle\Entity\Comment, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Comment }
        public: true
